services:
    wef:
        stdin_open: true
        tty: true
        privileged: true
        network_mode: host
        pid: host
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        image: finchsec/wef