name: DockerHub README update

on:
  push:
    branches:
      - 'main'
    paths:
      - README.md
  workflow_dispatch:

jobs:
  docker-readme-update:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v3
      -
        name: Update Docker repo description
        uses: peter-evans/dockerhub-description@v3.1.2
        with:
          readme-filepath: './docker/docker-README.md'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: finchsec/wef